
package estacionamiento;
//Se importan las librerias necesarias para el uso del codigo
import Metodos_sql.ConexionBD;
import static Metodos_sql.ConexionBD.PASSWORD;
import static Metodos_sql.ConexionBD.URL;
import static Metodos_sql.ConexionBD.USERNAME;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

//Se crea la funcion principal para el JFrame de la funcion datos de vehiculo con sus respectivas variables como sus sentencias preparadas y variables de conexion a la base de datos.
public class datosVehiculo extends javax.swing.JFrame {
    PreparedStatement ps;
    ResultSet rs;
    public static final String URL = "jdbc:mysql://localhost:3306/Estacionamiento";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    //Se genera la visualizacion del menu de forma centrada.
    public datosVehiculo() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        this.setTitle("Registro de nuevos vehiculos");
        mostrardatos("");
    }
    //Esta funcion se usa para mostrar los datos en la tabla Jtable
    void mostrardatos (String valor){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("No. Boleto");
        modelo.addColumn("ID acomodador");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Color");
        modelo.addColumn("Placas");
        modelo.addColumn("Observaciones");
        modelo.addColumn("Nivel");
        modelo.addColumn("Cajon");
        modelo.addColumn("Hora Entrada");
        modelo.addColumn("Hora Salida");
        modelo.addColumn("Estatus");
        modelo.addColumn("Pago total");
        tb_acomodadores.setModel(modelo);
        String sql="";
        if(valor.equals("")){
            sql="SELECT * FROM vehiculos";
        }else{
            sql="SELECT * FROM vehiculos WHERE idAcomodador='"+valor+"'";
        }
        Connection con=null;
        String []datos = new String[13];
        
        try{
            con = getConection();
            ps = con.prepareStatement("SELECT * FROM vehiculos");
            rs = ps.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                modelo.addRow(datos);
            }
            tb_acomodadores.setModel(modelo);
        } catch(Exception e){
            
        }
        
    }
    
    //Se crea el metodo de conxion a la base de datos para utilizarlo en los diferentes puntos del programa.
        public static Connection getConection(){
        Connection con = null;
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection)DriverManager.getConnection(URL,USERNAME,PASSWORD);
            System.out.println("Conexion exitosa");
            //JOptionPane.showMessageDialog(null, "Conexion exitosa");
            
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
    }
        
        
//Se crea el metodo para limpiar las cajas de texto una vez usadas ciertas funciones.
    private void limpiarCajas(){
        txt_marca.setText(null);
        txt_modelo.setText(null);
        txt_color.setText(null);
        txt_placas.setText(null);
        txt_observacion.setText(null);
        cbx_nivel.setSelectedIndex(0);
        cbx_cajon.setSelectedIndex(0);
        jd_HoraEntrada.setDate(null);
        jd_HoraSalida.setDate(null);
        cbx_estatus.setSelectedIndex(0);
        txt_idAcomodador.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_placas = new javax.swing.JTextField();
        txt_observacion = new javax.swing.JTextField();
        txt_noBoleto = new javax.swing.JTextField();
        cbx_nivel = new javax.swing.JComboBox<>();
        cbx_cajon = new javax.swing.JComboBox<>();
        cbx_estatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_idAcomodador = new javax.swing.JTextField();
        jd_HoraEntrada = new com.toedter.calendar.JDateChooser();
        jd_HoraSalida = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_acomodadores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_buscarIDacomodador = new javax.swing.JTextField();
        btn_buscarIDacomodador = new javax.swing.JButton();
        btn_salidaVehiculo = new javax.swing.JButton();
        btn_buscarVehiculo = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_mostrarTodo = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_costoHora = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_costoFraccion = new javax.swing.JTextField();
        btn_imprimirPago = new javax.swing.JButton();
        txt_totalPago = new javax.swing.JTextField();
        btn_regresar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Color");

        jLabel4.setText("Placas");

        jLabel5.setText("Observaciones");

        jLabel6.setText("Nivel");

        jLabel7.setText("Cajon");

        jLabel8.setText("Hora entrada");

        jLabel9.setText("Hora salida");

        jLabel10.setText("Estatus");

        jLabel11.setText("No boleto registrado");

        txt_noBoleto.setEnabled(false);

        cbx_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2", "3", "4" }));

        cbx_cajon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2", "3", "4", "5", "6", "7", "8" }));

        cbx_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2" }));

        jLabel12.setText("1 - Ocupado /   2 - Libre");

        jLabel14.setText("ID Acomodador que lo registra");

        jd_HoraEntrada.setDateFormatString("yyyy/MM/dd HH:mm:ss");

        jd_HoraSalida.setDateFormatString("yyyy/MM/dd HH:mm:ss");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de registros de boletos por acomodador"));

        tb_acomodadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_acomodadores.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tb_acomodadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de modificacion de registros"));

        jLabel15.setText("Buscar registros por ID acomodador");

        btn_buscarIDacomodador.setText("Buscar Registros");
        btn_buscarIDacomodador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarIDacomodadorActionPerformed(evt);
            }
        });

        btn_salidaVehiculo.setText("Salida vehiculo");
        btn_salidaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaVehiculoActionPerformed(evt);
            }
        });

        btn_buscarVehiculo.setText("Buscar vehiculo");
        btn_buscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarVehiculoActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar datos de vehiculo");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jLabel13.setText("Buscar boleto por No. boleto");

        btn_guardar.setText("Guardar nuevo vehiculo");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_mostrarTodo.setText("Mostrar todos los registros");
        btn_mostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarTodoActionPerformed(evt);
            }
        });

        jLabel18.setText("Costo x hora");

        jLabel19.setText("Costo x fraccion");

        btn_imprimirPago.setText("Imprimir pago");
        btn_imprimirPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirPagoActionPerformed(evt);
            }
        });

        txt_totalPago.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarVehiculo)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txt_buscarIDacomodador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarIDacomodador))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_salidaVehiculo)
                        .addGap(79, 79, 79)
                        .addComponent(btn_mostrarTodo)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(33, 33, 33)
                        .addComponent(txt_costoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_imprimirPago)
                            .addComponent(txt_costoFraccion))))
                .addGap(18, 18, 18)
                .addComponent(txt_totalPago, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_costoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_costoFraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_totalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarVehiculo)
                            .addComponent(jLabel15)
                            .addComponent(txt_buscarIDacomodador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarIDacomodador))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_actualizar)
                            .addComponent(btn_mostrarTodo)
                            .addComponent(btn_salidaVehiculo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_imprimirPago))
        );

        btn_regresar.setText("Regresar menu principal");
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });

        jLabel16.setText("Opciones con click derecho: Modificar = Se agregan los datos a las casillas para modificar (excepto fecha para seguridad de registros)");

        jLabel17.setText("Eliminar = Se eliminara un registro de forma automatica de la base de datos, se necesita seleccionar directamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addGap(48, 48, 48)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_placas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbx_cajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbx_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbx_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel12))
                                                .addComponent(jd_HoraEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                                .addComponent(jd_HoraSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_noBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_idAcomodador))))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_regresar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(360, 360, 360)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(497, 497, 497)
                                        .addComponent(jLabel17)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_observacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbx_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbx_cajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jd_HoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jd_HoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbx_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_noBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_idAcomodador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Se crea el metodo del boton guardar, el cual registrara el la base de datos el nuevo vehiculo con sus respectivos datos ingresados usando un Try-Catch con la funcion de saber si se encuentra el lugar (cajon) ocupado o libre.
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        Connection con=null;
        
        try{
            con = getConection();
            ps = con.prepareStatement("Select * FROM vehiculos WHERE (Nivel, Cajon, Estatus) = (?,?,?)");
            ps.setInt(1, cbx_nivel.getSelectedIndex());
            ps.setInt(2, cbx_cajon.getSelectedIndex());
            ps.setInt(3, cbx_estatus.getSelectedIndex());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Ese lugar esta ocupado, favor de escojer otro nivel y/o cajon diferente");
            }else{
            con = getConection();
            ps = con.prepareStatement("INSERT INTO vehiculos(Marca, Modelo, Color, Placas, Observaciones, Nivel, Cajon, HoraEntrada, Estatus, idAcomodador) VALUES(?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txt_marca.getText());
            ps.setString(2, txt_modelo.getText());
            ps.setString(3, txt_color.getText());
            ps.setString(4, txt_placas.getText());
            ps.setString(5, txt_observacion.getText());
            ps.setInt(6, cbx_nivel.getSelectedIndex());
            ps.setInt(7, cbx_cajon.getSelectedIndex());
            ps.setString(8, ((JTextField)jd_HoraEntrada.getDateEditor().getUiComponent()).getText());
            //ps.setString(9, ((JTextField)jd_HoraSalida.getDateEditor().getUiComponent()).getText());
            ps.setInt(9, cbx_estatus.getSelectedIndex());
            ps.setInt(10, Integer.parseInt(txt_idAcomodador.getText()));
            
            int res = ps.executeUpdate();
            
            if(res>0){
                JOptionPane.showMessageDialog(null, "Nuevo vehiculo guardado");
                limpiarCajas();
            } else{
                JOptionPane.showMessageDialog(null, "Error al guardar los datos del vehiculo, intente de nuevo");
                limpiarCajas();
            }
            
            con.close();
            }
            mostrardatos("");
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed
//Se crea la funcion para el boton regresar, el cual nos regresara al menu principal para elegir alguna otra funcion adicional.
    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        MenuPrincipal mPri = new MenuPrincipal();
        mPri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked
//Se crea la funcion del boton guscar vehiculo, el cual nos buscara en la base de datos el vehiculo ingresado usando el numero del boleto usando un Try-Catch.
    private void btn_buscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarVehiculoActionPerformed
        Connection con=null;
        
        try{
            con = getConection();
            ps = con.prepareStatement("Select * FROM vehiculos WHERE NoBoleto = ?");
            ps.setInt(1, Integer.parseInt(txt_buscar.getText()));
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                txt_marca.setText(rs.getString("Marca"));
                txt_modelo.setText(rs.getString("Modelo"));
                txt_color.setText(rs.getString("Color"));
                txt_placas.setText(rs.getString("Placas"));
                txt_observacion.setText(rs.getString("Observaciones"));
                cbx_nivel.setSelectedItem(rs.getString("Nivel"));
                cbx_cajon.setSelectedItem(rs.getString("Cajon"));
                jd_HoraEntrada.setDate(rs.getTimestamp("HoraEntrada"));
                jd_HoraSalida.setDate(rs.getTimestamp("HoraSalida"));
                cbx_estatus.setSelectedItem(rs.getString("Estatus"));
                txt_idAcomodador.setText(rs.getString("idAcomodador"));
                txt_noBoleto.setText(rs.getString("NoBoleto"));
            }else{
            JOptionPane.showMessageDialog(null,"No existe una vehiculo con ese numero de boleto");
            }
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_buscarVehiculoActionPerformed
//Se genera la funcion del boton salida de vehiculo, el cual en el momento de la salida se actualizaran los datos del vehiculo en la base de datos maracandolo como "libre".
    private void btn_salidaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaVehiculoActionPerformed
        Connection con=null;
        
        try{
            con = getConection();
            ps = con.prepareStatement("Select * FROM vehiculos WHERE NoBoleto = ?");
            ps.setInt(1, Integer.parseInt(txt_noBoleto.getText()));
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                //con = getConection();
                ps = con.prepareStatement("UPDATE vehiculos SET Marca=?, Modelo=?, Color=?, Placas=?, Observaciones=?, Nivel=?, Cajon=?, HoraEntrada=?, HoraSalida=?, Estatus=2, Pago=?, idAcomodador=? WHERE NoBoleto=?");
                ps.setString(1, txt_marca.getText());
                ps.setString(2, txt_modelo.getText());
                ps.setString(3, txt_color.getText());
                ps.setString(4, txt_placas.getText());
                ps.setString(5, txt_observacion.getText());
                ps.setInt(6, cbx_nivel.getSelectedIndex());
                ps.setInt(7, cbx_cajon.getSelectedIndex());
                ps.setString(8, ((JTextField)jd_HoraEntrada.getDateEditor().getUiComponent()).getText());
                ps.setString(9, ((JTextField)jd_HoraSalida.getDateEditor().getUiComponent()).getText());
                //ps.setInt(10, cbx_estatus.getSelectedIndex());
                ps.setInt(11, Integer.parseInt(txt_idAcomodador.getText()));
                
                
                int PagoH = Integer.parseInt(txt_costoHora.getText());
                int PagoF = Integer.parseInt(txt_costoFraccion.getText());
                int Suma = PagoH + PagoF;
                String totalPago = String.valueOf(Suma);
                txt_totalPago.setText(totalPago);
                ps.setInt(10, Suma);
                                
                ps.setInt(12, Integer.parseInt(txt_noBoleto.getText()));
                

            
                int res = ps.executeUpdate();
            
                if(res>0){
                JOptionPane.showMessageDialog(null, "Vehiculo dado de baja y guardado exitosamente");
                mostrardatos("");
                limpiarCajas();
                } else {
                JOptionPane.showMessageDialog(null, "Error al guardar la salida del vehiculo, intente de nuevo");
                limpiarCajas();
                }
            
                con.close();
            }else{
                JOptionPane.showMessageDialog(null,"Ese lugar esta ocupado, favor de escojer otro nivel y/o cajon diferente");
            }
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_salidaVehiculoActionPerformed
//Este boton filtra los datos de la BD usando el ID del acomodador
    private void btn_buscarIDacomodadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarIDacomodadorActionPerformed
        mostrardatos(txt_buscarIDacomodador.getText());
    }//GEN-LAST:event_btn_buscarIDacomodadorActionPerformed
//Este boton muestra todos los datos de la BD sin filtro
    private void btn_mostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarTodoActionPerformed
        mostrardatos("");
    }//GEN-LAST:event_btn_mostrarTodoActionPerformed
//Este menu item se usa para seleccionar de forma direta en la BD para actualizar datos
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = tb_acomodadores.getSelectedRow();
        
        if(fila>=0){
            txt_noBoleto.setText(tb_acomodadores.getValueAt(fila, 0).toString());
            txt_idAcomodador.setText(tb_acomodadores.getValueAt(fila, 1).toString());
            txt_marca.setText(tb_acomodadores.getValueAt(fila, 2).toString());
            txt_modelo.setText(tb_acomodadores.getValueAt(fila, 3).toString());
            txt_color.setText(tb_acomodadores.getValueAt(fila, 4).toString());
            txt_placas.setText(tb_acomodadores.getValueAt(fila, 5).toString());
            txt_observacion.setText(tb_acomodadores.getValueAt(fila, 6).toString());
            cbx_nivel.setSelectedIndex(Integer.parseInt(tb_acomodadores.getValueAt(fila, 7).toString()));
            cbx_cajon.setSelectedIndex(Integer.parseInt(tb_acomodadores.getValueAt(fila, 8).toString()));
            cbx_estatus.setSelectedIndex(Integer.parseInt(tb_acomodadores.getValueAt(fila, 11).toString()));
        }else{
            JOptionPane.showMessageDialog(null, "No selecciono una fila especifica");
        }
        
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//Este boton actualiza los datos que se cambiaron en los campos
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Connection con=null;
        
        try{
            con = getConection();
            ps = con.prepareStatement("UPDATE vehiculos SET idAcomodador='"+txt_idAcomodador.getText()+"', Marca='"+txt_marca.getText()+"', Modelo='"+txt_modelo.getText()+"', Color='"+txt_color.getText()+"', Placas='"+txt_placas.getText()+"', Observaciones='"+txt_observacion.getText()+"', Nivel='"+cbx_nivel.getSelectedIndex()+"', Cajon='"+cbx_cajon.getSelectedIndex()+"', Estatus='"+cbx_estatus.getSelectedIndex()+"' WHERE NoBoleto ='"+txt_noBoleto.getText()+"'");
            int res = ps.executeUpdate();
            mostrardatos("");
            limpiarCajas();
            JOptionPane.showMessageDialog(null, "Los datos del vehiculo se actualizaron correctamente");
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed
//Este menu item se encarga de borrar un registro seleccionado directamente en la BD
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = tb_acomodadores.getSelectedRow();
        String cod;
        cod = tb_acomodadores.getValueAt(fila, 0).toString();
        Connection con=null;
        
        try{
            con = getConection();
            ps = con.prepareStatement("DELETE FROM vehiculos WHERE NoBoleto ='"+cod+"'");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Los datos del vehiculo se borraron correctamente");
            mostrardatos("");
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_imprimirPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirPagoActionPerformed
        
        MessageFormat header= new MessageFormat("Reporte de vehiculos");
        MessageFormat footer= new MessageFormat("Pagina {0,number,integer}");
        try{
            
            tb_acomodadores.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("No se puede imprimir", e.getMessage());
        }
    }//GEN-LAST:event_btn_imprimirPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datosVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datosVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datosVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datosVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datosVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscarIDacomodador;
    private javax.swing.JButton btn_buscarVehiculo;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_imprimirPago;
    private javax.swing.JButton btn_mostrarTodo;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_salidaVehiculo;
    private javax.swing.JComboBox<String> cbx_cajon;
    private javax.swing.JComboBox<String> cbx_estatus;
    private javax.swing.JComboBox<String> cbx_nivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jd_HoraEntrada;
    private com.toedter.calendar.JDateChooser jd_HoraSalida;
    private javax.swing.JTable tb_acomodadores;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_buscarIDacomodador;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_costoFraccion;
    private javax.swing.JTextField txt_costoHora;
    private javax.swing.JTextField txt_idAcomodador;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_noBoleto;
    private javax.swing.JTextField txt_observacion;
    private javax.swing.JTextField txt_placas;
    private javax.swing.JTextField txt_totalPago;
    // End of variables declaration//GEN-END:variables
}
