
package estacionamiento;

//import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class nominaEmpleados extends javax.swing.JFrame {
    PreparedStatement ps1;
    PreparedStatement ps2;
    ResultSet rs1;
    ResultSet rs2;
    public static final String URL = "jdbc:mysql://localhost:3306/Estacionamiento";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    
    public nominaEmpleados() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        this.setTitle("Reporte de nomina de acomodadores");
    }

    //Se crea la conexion a la BD
    public static Connection getConection(){
        Connection con = null;
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection)DriverManager.getConnection(URL,USERNAME,PASSWORD);
            System.out.println("Conexion exitosa");
            //JOptionPane.showMessageDialog(null, "Conexion exitosa");
            
        }catch(Exception e){
            System.out.println(e);
        }
        return con;
    }
    
    void mostrardatos (String valor){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Acom");
        modelo.addColumn("Nombre Acom");
        modelo.addColumn("Cantidad de serv x semana");
        modelo.addColumn("Sueldo semanal");
        modelo.addColumn("Comision total");
        
        tb_acomodadores.setModel(modelo);
        
        /*String sql="";
        if(valor.equals("")){
            try{
            sql="SELECT idAcomodador FROM vehiculos WHERE idAcomodador = ?";
            ps.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            sql="SELECT Nombre FROM acomodadores WHERE idAcomodador = ?";
            ps.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            }catch(Exception e){
            System.err.println(e);
            }
        }
        */
        Connection con=null;
        String []datos = new String[5];
        
        try{
            con = getConection();
            ps1 = con.prepareStatement("SELECT * FROM vehiculos WHERE idAcomodador = ?");
            ps1.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            rs1 = ps1.executeQuery();
            /*ps2 = con.prepareStatement("SELECT Nombre FROM acomodadores WHERE idAcomodador = ?");
            ps2.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            rs2 = ps2.executeQuery();*/
            while(rs1.next()){
                datos[0]=rs1.getString(2);
                /*datos[1]=rs2.getString(2);
                /*datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);*/
                modelo.addRow(datos);
            }
            /*    ps2 = con.prepareStatement("SELECT * FROM acomodadores WHERE idAcomodador = ?");
                ps2.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
                rs2 = ps2.executeQuery();
                while(rs1.next()){
                    datos[1]=rs2.getString(2);
                    /*datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);*/
                    //modelo.addRow(datos);
                
            
            tb_acomodadores.setModel(modelo);
        }catch(Exception e)
            {
            
            }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_acomodadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_noAcomo = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros del acomodador"));

        tb_acomodadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_acomodadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Introduce el numero de empleado a buscar");

        btn_buscar.setText("Buscar acomodador");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar a menu principal");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_noAcomo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btn_regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_noAcomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btn_regresar)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Este boton nos permite regresar al menu principal.
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        MenuPrincipal mPri = new MenuPrincipal();
        mPri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        Connection con=null;
        
        try{
            con = getConection();
            ps1 = con.prepareStatement("Select * FROM acomodadores WHERE idAcomodador = ?");
            ps1.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            rs1 = ps1.executeQuery();
            
            /*ps2 = con.prepareStatement("SELECT Nombre FROM acomodadores WHERE idAcomodador = ?");
            ps2.setInt(1, Integer.parseInt(txt_noAcomo.getText()));
            rs2 = ps2.executeQuery();*/
            
            if(rs1.next()){
                mostrardatos("");
                
            }else{
            JOptionPane.showMessageDialog(null,"No existe una acomodador con ese numero de ID");
            }
        }catch(Exception e){
            System.err.println(e);
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nominaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nominaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nominaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nominaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nominaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_acomodadores;
    private javax.swing.JTextField txt_noAcomo;
    // End of variables declaration//GEN-END:variables
}
